### ISSUE TITLE
Client immediately disconnects (Asterisk 1.6.2.6)

### ISSUE THREAD

**Issue by vetash** [clue/php-ami-react#42]
Hello! I have no succes to use this library with my gsm gateway (Yeastar TG400) based on linux with asterisk 1.6.2.6.

Here is some details:
I copypasted this example to test.php:
```<?php

include __DIR__."/vendor/autoload.php";
use Clue\React\Ami\Factory;
use Clue\React\Ami\Client;
use Clue\React\Ami\ActionSender;
use Clue\React\Ami\Protocol\Response;


$loop = React\EventLoop\Factory::create();
$factory = new Factory($loop);
$target = isset($argv[1]) ? $argv[1] : '<MYUSER>:<MYPASS>@<MYHOST>;
$factory->createClient($target)->then(function (Client $client) use ($loop) {
    echo 'Client connected. Use STDIN to send CLI commands via asterisk AMI.' . PHP_EOL;
    $sender = new ActionSender($client);
    $sender->events(false);
    $sender->listCommands()->then(function (Response $response) {
        echo 'Commands: ' . implode(', ', array_keys($response->getFields())) . PHP_EOL;
    });
    $client->on('close', function() use ($loop) {
        echo 'Closed' . PHP_EOL;
        $loop->removeReadStream(STDIN);
    });
    $loop->addReadStream(STDIN, function () use ($sender) {
        $line = trim(fread(STDIN, 4096));
        echo '<' . $line . PHP_EOL;
        $sender->command($line)->then(
            function (Response $response) {
                echo $response->getCommandOutput() . PHP_EOL;
            },
            function (Exception $error) use ($line) {
                echo 'Error executing "' . $line . '": ' . $error->getMessage() . PHP_EOL;
            }
        );
    });
}, 'var_dump');
$loop->run();
```
On client:
```root@server:/tmp/asterisk# php test.php
Client connected. Use STDIN to send CLI commands via asterisk AMI.
Closed```


On server:
```Verbosity is at least 3
  == Manager '<CLIENTUSER>' logged on from <CLIENTHOST>
  == Manager '<CLIENTUSER>' logged off from <CLIENTHOST>
TG400*CLI> 
```

I've tryed to send command with `$sender->("<command>")->...` but have no succes too. 

Can you help me to debug this?

**Comment by clue** [comment]
From the logs you've provided it looks like the client is immediately disconnected. I would suggest adding an `error` and `event` listener to see if that's the reason for this:

```php
$client->on('event', function (Event $event) {
    var_dump($event);
});
$client->on('error', function (Exception $e) {
    echo $e . PHP_EOL;
});
```

**Comment by vetash** [comment]
```Client connected. Use STDIN to send CLI commands via asterisk AMI.
Closed
exception 'Clue\React\Ami\Protocol\UnexpectedMessageException' with message 'Unexpected message with action ID "" received' in /tmp/asterisk/vendor/clue/ami-react/src/Client.php:77
Stack trace:
#0 /tmp/asterisk/vendor/clue/ami-react/src/Client.php(43): Clue\React\Ami\Client->handleMessage(Object(Clue\React\Ami\Protocol\Response))
#1 [internal function]: Clue\React\Ami\Client->Clue\React\Ami\{closure}('Response: Succe...')
#2 /tmp/asterisk/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): call_user_func_array(Object(Closure), Array)
#3 /tmp/asterisk/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#4 [internal function]: React\Stream\Util::React\Stream\{closure}('Response: Succe...')
#5 /tmp/asterisk/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(70): call_user_func_array(Object(Closure), Array)
#6 /tmp/asterisk/vendor/react/stream/src/DuplexResourceStream.php(186): Evenement\EventEmitter->emit('data', Array)
#7 [internal function]: React\Stream\DuplexResourceStream->handleData(Resource id #43, Object(React\EventLoop\StreamSelectLoop))
#8 /tmp/asterisk/vendor/react/event-loop/src/StreamSelectLoop.php(236): call_user_func(Array, Resource id #43, Object(React\EventLoop\StreamSelectLoop))
#9 /tmp/asterisk/vendor/react/event-loop/src/StreamSelectLoop.php(205): React\EventLoop\StreamSelectLoop->waitForStreamActivity(NULL)
#10 /tmp/asterisk/test.php(43): React\EventLoop\StreamSelectLoop->run()
#11 {main}
```

**Comment by clue** [comment]
Here's how the `Client` works:

Whenever you send an "action", it uses an auto incrementing ID starting with `ActionId: 1`. This is required because the server will include the same `ActionId: 1` in its response message. The client then uses this information to map incoming responses to the outgoing requests to figure out when a result has been received. This is important because the client may send multiple actions at once and the server is not required to respond in the exact same order.

Your output suggests that the `Client` receives a message without an `ActionId` field - however, it never actually sends such a message.

I recall there was an error in the somewhat outdated "astmanproxy" which borked the `ActionId` fields, do you happen to use this?

Other than that, I would suggest debugging the `Client::handleMessage()` method to see what kind of incoming message is being handled here.

**Comment by vetash** [comment]
Ok, i have added:
```
...
 /** @internal */
    public function handleMessage(Message $message)
    {
        var_dump($message);
        if ($message instanceof Event) {
            $this->emit('event', array($message));
            return;
...
```
To `Client.php`

And run script:

```
object(Clue\React\Ami\Protocol\Response)#46 (1) {
  ["fields":protected]=>
  array(3) {
    ["Response"]=>
    string(7) "Success"
    ["ActionID"]=>
    string(1) "1"
    ["Message"]=>
    string(23) "Authentication accepted"
  }
}
Client connected. Use STDIN to send CLI commands via asterisk AMI.
object(Clue\React\Ami\Protocol\Response)#46 (1) {
  ["fields":protected]=>
  array(2) {
    ["Response"]=>
    string(7) "Success"
    ["Events"]=>
    string(3) "Off"
  }
}
Closed
```

**Comment by vetash** [comment]
After commented:
`//    $sender->events(false);`
All works now. 

What does this code:
```
public function events($eventMask)
    {
        if ($eventMask === false) {
            $eventMask = 'off';
        } elseif ($eventMask === true) {
            $eventMask = 'on';
        } else {
            $eventMask = implode(',', $eventMask);
        }

        return $this->request('Events', array('EventMask' => $eventMask));
    }
```
in `ActionSender.php` ?

**Comment by clue** [comment]
Your log output suggests that the first action (login) worked correctly and your second action (events) returned a success message without an `ActionId`. I suppose this may be related to an old Asterisk version, but if you're happy with not issuing this action in the first place, I'm happy this is resolved for you :+1: 

Here's what the `Action: Events` does:

> Enable/Disable sending of events to this manager client.

See https://wiki.asterisk.org/wiki/display/AST/Asterisk+13+ManagerAction_Events or https://www.voip-info.org/wiki/view/Asterisk+Manager+API+Action+Events

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:
